type ReportCenterProps = {
  reports: string[];
};

export function ReportCenter({ reports }: ReportCenterProps) {
  return (
    <section>
      <h2>Enterprise Reports</h2>

      <p>Automated construction intelligence reports generated by Astra AI.</p>

      <ul>
        {reports.map((report) => (
          <li key={report}>{report}</li>
        ))}
      </ul>
    </section>
  );
}
