export function ReportCenter() {
  return (
    <section>
      <h2>
        Enterprise Reports
      </h2>

      <p>
        Automated construction intelligence reports generated by Astra AI.
      </p>

      <ul>
        <li>Weekly Operations Report</li>
        <li>Asset Performance Report</li>
        <li>Risk Analysis Report</li>
      </ul>
    </section>
  );
}
