<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Astra.Organization.Domain\Astra.Organization.Domain.csproj" />
    <ProjectReference Include="..\Astra.Organization.Contracts\Astra.Organization.Contracts.csproj" />
  </ItemGroup>

</Project>